# Generated by Django 2.2.5 on 2019-09-30 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TechnicalCourses', '0003_auto_20190930_1026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allcourses',
            name='startedfrom',
            field=models.DateTimeField(verbose_name='date started'),
        ),
    ]
