# Generated by Django 2.2.5 on 2019-09-30 05:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TechnicalCourses', '0005_auto_20190930_1059'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='allcourses',
            name='startedfrom',
        ),
    ]
